spring.application.name=backend
firebase.credentials.path=src/main/resources/askvocate-firebase-adminsdk-fbsvc-495e4025c9.json
firebase.storage.bucket=askvocate.appspot.com

jwt.secret=your-256-bit-secret-key-here-change-this
jwt.expiration=86400000